apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v3.3.2/manifests/install.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argo-cd
    target:
      kind: ClusterRoleBinding
